### PR TITLE
Re-link notebook using Neuron 7.4

### PR DESCRIPTION
**Pull request by antonelepfl**

### CODE REVIEW

**Comment by antonelepfl** [comment]
@alex4200 Based on what Collab team told me in this [ticket](https://support.humanbrainproject.eu/#ticket/zoom/2262) the default Neuron version should be still 7.4 so students should not have any issue for now.
I created this PR so you can test this notebook and see if this fix the issue for you and also to have a backup plan in case they need to change the version to 7.6 as default.

**Comment by alex4200** [comment]
@antonelepfl You refer to the MOOC notebook Reconstruction/Week 4/ Excercise 1?

**Comment by antonelepfl** [comment]
Exaclty

**Comment by alex4200** [comment]
Locally tested, seems to work after some restarts/reloads.

**Comment by alex4200** [comment]
Can this PR me merged?

**Comment by antonelepfl** [comment]
I would prefer not to touch the notebook until we have users with issues or the default version of Neuron in Collab change.
I did it just to know how we should change the notebooks in the case I mentioned above.

**Pull request closed without merging**
